spring:
  datasource:
    url: jdbc:mysql://localhost:3307/amit_dev
    username: amit_dev_user
    password: amit
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true